/** Génère MEMO.md depuis contenu.js : le mémo ne peut pas diverger du show. */
import { ETAPES } from '../src/contenu.js';
import { writeFile } from 'node:fs/promises';

const l = [];
l.push('# Mémo — « Nael, la voix de la T4 »');
l.push('');
l.push('## Lancer la présentation');
l.push('');
l.push('1. Copier **`index.html`** sur une clé USB (un seul fichier, rien d’autre à prendre).');
l.push('2. Double-cliquer dessus. Ça marche **sans Internet et sans serveur**.');
l.push('3. Cliquer sur **« ▶ Lancer le show »** — ce clic est obligatoire : c’est lui qui');
l.push('   autorise le son et déclenche le plein écran.');
l.push('4. Ne rien dire pendant les 10 premières secondes. L’intro fait le travail.');
l.push('');
l.push('> **Avant de passer** : vérifier que le son du PC n’est pas coupé et que le');
l.push('> vidéoprojecteur reçoit l’audio. Sans son, l’intro perd la moitié de son effet.');
l.push('');
l.push('## Les touches');
l.push('');
l.push('| Touche | Effet |');
l.push('| --- | --- |');
l.push('| **→** · **Espace** · **clic** · **PageDown** | Scène suivante |');
l.push('| **←** · **PageUp** | Scène précédente |');
l.push('| **N** | Afficher / masquer mes notes |');
l.push('| **M** | Couper / remettre le son |');
l.push('| **F** | Plein écran |');
l.push('| **R** | Rejouer la scène en cours |');
l.push('| **P** | Forcer le mode performance (si ça rame) |');
l.push('| **A** / **B** / **C** | Révéler la réponse du quiz |');
l.push('| **H** | Rappel des touches à l’écran |');
l.push('| **Échap** | Ne casse rien : sort juste du plein écran (**F** pour y revenir) |');
l.push('');
l.push('Une télécommande de présentation fonctionne telle quelle (elle envoie');
l.push('PageDown / PageUp).');
l.push('');
l.push('## Ce que je dis, scène par scène');
l.push('');
l.push('Total visé : **environ 1 min 30**. Les notes sont aussi affichables à l’écran');
l.push('avec la touche **N** (elles ne sont visibles que par moi si j’ai un écran de');
l.push('retour ; sinon, ne pas les afficher pendant la projection).');
l.push('');
ETAPES.forEach((e, i) => {
  l.push(`### ${String(i).padStart(2, '0')} — ${e.titre ?? 'Intro'}`);
  l.push('');
  l.push(e.notes);
  l.push('');
});
l.push('## Si ça se passe mal');
l.push('');
l.push('| Problème | Solution |');
l.push('| --- | --- |');
l.push('| Ça rame | Touche **P** (mode performance). La bascule est aussi automatique. |');
l.push('| Pas de son | Touche **M**. Sinon, vérifier le volume du poste. |');
l.push('| Écran noir au lancement | Le PC n’a pas de 3D : la version 2D de secours prend le relais automatiquement, avec le même contenu et les mêmes touches. |');
l.push('| Je me suis perdu dans les scènes | **←** pour revenir, **R** pour rejouer la scène. |');
l.push('| Une animation est partie trop vite | **R** rejoue la scène en cours proprement. |');
l.push('');
await writeFile(new URL('../MEMO.md', import.meta.url), l.join('\n'), 'utf8');
console.log('MEMO.md écrit');
